config/routes.rb
Mapeamento::Application.routes.draw do

  
  get "sessions/new"

  resources :pessoas

  resources :contatos
  match "contatos/new/:obj_type/:obj_id" => 'contatos#new', as: "novo_contato"
  match "contatos/edit/:id/:obj_type/:obj_id" => 'contatos#edit', as: "editar_contato"

  resources :laboratorios

  resources :departamentos

  resources :unidades

  resources :redes, :except => :show do
    resources :palavras
  end
  root to: "application#home", as: "home"
  match 'administracao' => 'application#administracao', as: "administracao"
  match 'construcao' => 'application#under_construction'
  match 'laboratorios/new/:departamento_id' => 'laboratorios#new', as: "novo_laboratorio_com_departamento"
  match 'departamentos/new/:unidade_id' => 'departamentos#new', as: "novo_departamento_com_unidade"
  match 'palavras' => 'palavras#index'  
  

end

app/models/unidade.rb
class Unidade < ActiveRecord::Base
  attr_accessible :bairro, :cidade, :complemento, :logradouro, :nome, :numero, :uf
  validates :nome, presence: true
  has_many :departamentos
  has_one :contato, as: :obj

  def to_s
    nome
  end
end

app/controllers/unidades_controller.rb
#!/bin/env ruby
# encoding: utf-8
class UnidadesController < ApplicationController
  # GET /unidades
  # GET /unidades.json
  def index
    @unidades = Unidade.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @unidades }
    end
  end

  # GET /unidades/1
  # GET /unidades/1.json
  def show
    @unidade = Unidade.find(params[:id])
    @departamentos = @unidade.departamentos
    @contato = @unidade.contato 

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @unidade }
    end
  end

  # GET /unidades/new
  # GET /unidades/new.json
  def new
    @unidade = Unidade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @unidade }
    end
  end

  # GET /unidades/1/edit
  def edit
    @unidade = Unidade.find(params[:id])
  end

  # POST /unidades
  # POST /unidades.json
  def create
    @unidade = Unidade.new(params[:unidade])

      if @unidade.save
        flash[:success] = "Unidade #{@unidade.nome} cadastrado(a)!"
        redirect_to @unidade
      else
        flash[:error] = @unidade.errors
        render action: "new"
      end
  end

  # PUT /unidades/1
  # PUT /unidades/1.json
  def update
    @unidade = Unidade.find(params[:id])

    respond_to do |format|
      if @unidade.update_attributes(params[:unidade])
        format.html { redirect_to @unidade, notice: 'Unidade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unidades/1
  # DELETE /unidades/1.json
  def destroy
    @unidade = Unidade.find(params[:id])
    @unidade.destroy

    respond_to do |format|
      format.html { redirect_to unidades_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/unidades_helper.rb
module UnidadesHelper
end

app/views/unidades/_form.html.erb
<%= simple_form_for(@unidade, html: {class: 'form-horizontal'}) do |f| %>
<%= f.error_notification %>
<div class="form-inputs">
	<%= f.input :nome, label: 'Unidade' %> 
	<br />
	<h2><small>Endereço</small></h2>
	<%= f.input :logradouro, input_html: {class: 'span6'}, placeholder: "Rua Miguel de Frias" %>
	<%= f.input :numero, label: "Número", placeholder: "9", input_html: {class: 'span1'}, as: :string %>
	<%= f.input :bairro %>
	<%= f.input :cidade %>
	<%= f.input :uf, label: 'UF', input_html: {class: 'span1'} %>
	<%= f.input :complemento, placeholder: "Bloco Z", input_html: {class: 'span2'} %>
</div>
<%= f.button :submit, "Salvar",class: "btn btn-primary" %>
<%= link_to 'Voltar', unidades_path, class: 'btn' %>
<% end %> 

app/views/unidades/edit.html.erb
<div class="page-header">
  <h1>Editar Unidade de Ensino</h1>
</div>
<%= render 'form' %>

app/views/unidades/index.html.erb
<div class="page-header">
	<h1>Unidades de Ensino</h1>
</div>
<% if (@unidades.empty?) %>
	<%= bloco_vazio "Clique em Cadastrar Unidade.", "", class: "well span10 construcao" %>
<% else %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Unidade</th>
      <th>Departamentos</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
<% @unidades.each do |unidade| %>
      <tr>
        <td><%= link_to unidade.nome , unidade %></td>
        <td><%= unidade.departamentos.count %></td>
        <td>
          <%= link_to "Informações", unidade, class: 'btn btn-small' %>
          <%= link_to "Editar", edit_unidade_path(unidade), class: 'btn btn-small' %>
          <%= link_to 'Remover', unidade_path(unidade), confirm: 'Tem certeza?', method: :delete, class: "btn btn-small btn-info" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<%= botao_com_icone "Cadastrar Unidade", new_unidade_path, "icon-plus icon-white", btn_class: "btn-primary" %>
<%= link_to 'Início', administracao_path, class: 'btn' %>

app/views/unidades/new.html.erb
<div class="page-header">
  <h1>Cadastrar Unidade de Ensino</h1>
</div>
<%= render 'form' %>

app/views/unidades/show.html.erb
<div class="page-header">
	<h1><%= @unidade.nome %> <small> Unidade de Ensino</small></h1>
</div>
<div class="row-fluid linha-conteudo">
	<div class="span5 well">
		<h3>Informações <small><%= botao_com_icone "Editar", edit_unidade_path(@unidade), "icon-edit icon-white", btn_class: "btn btn-mini btn-primary edit-button" %></small></h3>
		<hr>
		<p>
			<b>Coordenador:</b>
		</p>
		<p>
			<b>Endereço:</b>
			<br />
			<%= @unidade.logradouro %>, <%= @unidade.numero %>
			<br />
			<%= @unidade.complemento %> - <%= @unidade.bairro %> - <%= @unidade.cidade %>, <%= @unidade.uf %>
		</p>
	</div>
		<% if (@departamentos.empty?) %>
			<% btn_vazio = botao_com_icone "Cadastrar Departamento", novo_departamento_com_unidade_path(@unidade.id), "icon-plus icon-white", class: "btn btn-primary btn-large"%>
			<%= bloco_vazio "Clique em Cadastrar Unidade.", btn_vazio, class: "well span10 construcao" %>
		<% else %>
			<div class="well span5">
				<h3>Departamentos Cadastrados <small><%= botao_com_icone "Cadastrar Departamento", novo_departamento_com_unidade_path(@unidade.id), "icon-plus icon-white", btn_class: "btn-primary btn-mini edit-button" %></small></h3>
				<hr>
				<table class="table table-striped">
					<thead>
						<tr>
							<th>Departamento</th>
							<th>Coordenador</th>
						</tr>
					</thead>
					<tbody>
						<% @departamentos.each do |departamento|%>
						<tr>
							<td><%= link_to departamento.nome, departamento %></td>
							<td>Professor</td>
						</tr>
						<% end %>
					</tbody>
				</table>
			</div>
		<% end %>
</div>
<div class="row-fluid linha-conteudo">
	<%= bloco_contato contato: @contato, obj: @unidade, class: "span5" %>
</div>
</div>
<br />
<%= link_to 'Editar', edit_unidade_path(@unidade), class: 'btn' %>
<%= link_to 'Voltar', unidades_path, class: 'btn'	 %> 