config/routes.rb
Mapeamento::Application.routes.draw do

  
  get "sessions/new"

  resources :pessoas

  resources :contatos
  match "contatos/new/:obj_type/:obj_id" => 'contatos#new', as: "novo_contato"
  match "contatos/edit/:id/:obj_type/:obj_id" => 'contatos#edit', as: "editar_contato"

  resources :laboratorios

  resources :departamentos

  resources :unidades

  resources :redes, :except => :show do
    resources :palavras
  end
  root to: "application#home", as: "home"
  match 'administracao' => 'application#administracao', as: "administracao"
  match 'construcao' => 'application#under_construction'
  match 'laboratorios/new/:departamento_id' => 'laboratorios#new', as: "novo_laboratorio_com_departamento"
  match 'departamentos/new/:unidade_id' => 'departamentos#new', as: "novo_departamento_com_unidade"
  match 'palavras' => 'palavras#index'  
  

end

app/models/rede.rb
class Rede < ActiveRecord::Base
  attr_accessible :nome
  attr_accessible :descricao
  has_many :palavras
end

app/controllers/redes_controller.rb
class RedesController < ApplicationController
  # GET /redes
  # GET /redes.json
  def index
    @redes = Rede.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @redes }
    end
  end

  # GET /redes/new
  # GET /redes/new.json
  def new
    @rede = Rede.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @rede }
    end
  end

  # GET /redes/1/edit
  def edit
    @rede = Rede.find(params[:id])
  end

  # POST /redes
  # POST /redes.json
  def create
    @rede = Rede.new(params[:rede])

    respond_to do |format|
      if @rede.save
        #msg sucesso
        format.html { redirect_to redes_path }
      else
        #msg erro
        format.html { render action: "new" }
      end
    end
  end

  # PUT /redes/1
  # PUT /redes/1.json
  def update
    @rede = Rede.find(params[:id])

    respond_to do |format|
      if @rede.update_attributes(params[:rede])
        format.html { redirect_to redes_path }
        #msg sucessi
      else
        format.html { render action: "edit" }
        #msg erro
      end
    end
  end

  # DELETE /redes/1
  # DELETE /redes/1.json
  def destroy
    @rede = Rede.find(params[:id])
    @rede.destroy

    respond_to do |format|
      format.html { redirect_to redes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/redes_helper.rb
module RedesHelper
end

app/views/redes/_form.html.erb
<%= form_for(@rede) do |f| %>
<% if @rede.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@rede.errors.count, "error") %> prohibited this rede from being saved:</h2>
	<ul>
		<% @rede.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="row-fluid">
	<div class="field">
		<%= f.text_field :nome, style: "position:relative;top:4px;"%>
		<%= f.submit "Salvar", class: "btn btn-primary" %>
	</div>
		<p>Descrição:</p>
		<%= f.text_area :descricao ,class: "input-xlarge" %>
</div>
<% end %> 

app/views/redes/edit.html.erb
<div class="page-header">
	<h1><%= @rede.nome %></h1>
</div>
<%= form_for(@rede) do |f| %>
<% if @rede.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@rede.errors.count, "error") %> prohibited this rede from being saved:</h2>
	<ul>
		<% @rede.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="row-fluid">
	<div class="field">
		<%= f.text_field :nome, style: "position:relative;top:4px;", class: "span4"%>
	</div>
		<p>Descrição:</p>
		<%= f.text_area :descricao , style:"margin-left:0",class: "input-xlarge span4", rows: "12" %>
</div>
<%= link_to 'Voltar', redes_path, class: "btn" %>
<%= f.submit "Salvar", class: "btn btn-primary" %>
<% end %> 

app/views/redes/index.html.erb
<div class="page-header">
	<h1>Redes Temáticas</h1>
</div>
<% if @redes.any? %>
	<% @redes.each do |rede| %>
<div class="row-fluid">
	<div class="well">
		<%= link_to  rede.nome, rede_palavras_path(rede), class:"rede_tematica" %>
		<p><%= rede.descricao %></p>
		<div class="row-fluid controles">
			<%= link_to 'Alterar Informações', edit_rede_path(rede), class: "btn"%>
			<%= link_to 'Gerenciar Palavras-Chave', rede_palavras_path(rede), class: "btn"%>
			<%= link_to 'Remover', rede, confirm: 'Tem certeza que quer remover esta rede temática?', method: :delete, class: "btn btn-info" %>		
		</div>
	</div>
</div>
	<% end %>
<% else %>
<div class="row-fluid">
	<%= bloco_vazio "Clique em Cadastrar Rede Temática", "",class: "span10 well construcao"%>
</div>
<% end %>

<%= botao_com_icone "Cadastrar Rede Temática", new_rede_path, "icon-plus icon-white", btn_class: "btn-primary" %>
<%= link_to 'Início', administracao_path, class: 'btn' %>

app/views/redes/new.html.erb
<div class="page-header">
	<h1>Criar Rede Temática</h1>
</div>

<%= form_for(@rede) do |f| %>
<% if @rede.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@rede.errors.count, "error") %> prohibited this rede from being saved:</h2>
	<ul>
		<% @rede.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>
<div class="row-fluid">
	<div class="field">
		<%= f.text_field :nome, style: "position:relative;top:4px;", class: "span4"%>
	</div>
		<p>Descrição:</p>
		<%= f.text_area :descricao , style:"margin-left:0",class: "input-xlarge span4", rows: "12" %>
</div>
<%= link_to 'Voltar', redes_path, class: "btn" %>
<%= f.submit "Salvar", class: "btn btn-primary" %>
<% end %> 

app/views/redes/show.html.erb
<div class="page-header">
	<h1><%= @rede.nome %></h1>
</div>

<p>
  <b>Descrição:</b>
  <br /><%= @rede.descricao %>
</p>
<p>
  <b>Palavras Chave:</b>
  <% @palavras.each do |palavra| %>
  	<br /><span class="label label-info"><%= palavra.expressao %></span>
  <% end %>
</p>
<form class="well form-inline">
	<input type="text" class="span3" placeholder="Nova Palavra Chave" id="palavra_form">
	<button type="submit" class="btn btn-primary" id="palavra_submit">Adicionar</button>
</form>

<%= link_to 'Alterar Informações', edit_rede_path(@rede), class: "btn" %> <%= link_to 'Voltar', redes_path, class: "btn" %>