config/routes.rb
Mapeamento::Application.routes.draw do

  
  get "sessions/new"

  resources :pessoas

  resources :contatos
  match "contatos/new/:obj_type/:obj_id" => 'contatos#new', as: "novo_contato"
  match "contatos/edit/:id/:obj_type/:obj_id" => 'contatos#edit', as: "editar_contato"

  resources :laboratorios

  resources :departamentos

  resources :unidades

  resources :redes, :except => :show do
    resources :palavras
  end
  root to: "application#home", as: "home"
  match 'administracao' => 'application#administracao', as: "administracao"
  match 'construcao' => 'application#under_construction'
  match 'laboratorios/new/:departamento_id' => 'laboratorios#new', as: "novo_laboratorio_com_departamento"
  match 'departamentos/new/:unidade_id' => 'departamentos#new', as: "novo_departamento_com_unidade"
  match 'palavras' => 'palavras#index'  
  

end

app/models/departamento.rb
class Departamento < ActiveRecord::Base
  attr_accessible :nome, :unidade_id, :unidade
  belongs_to :unidade
  has_many :laboratorios
  has_one :contato, as: :obj
  
  def to_s
    "#{nome}"
  end
end

app/controllers/departamentos_controller.rb
class DepartamentosController < ApplicationController
  # GET /departamentos
  # GET /departamentos.json
  def index
    @departamentos = Departamento.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @departamentos }
    end
  end

  # GET /departamentos/1
  # GET /departamentos/1.json
  def show
    @departamento = Departamento.find(params[:id])
    @contato = @departamento.contato
    @laboratorios = @departamento.laboratorios 
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @departamento }
    end
  end

  # GET /departamentos/new
  # GET /departamentos/new.json
  def new
    @departamento = Departamento.new
    @departamento.unidade = Unidade.find(params[:unidade_id]) if params[:unidade_id]
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @departamento }
    end
  end

  # GET /departamentos/1/edit
  def edit
    @departamento = Departamento.find(params[:id])
  end

  # POST /departamentos
  # POST /departamentos.json
  def create
    @departamento = Departamento.new(params[:departamento])

    respond_to do |format|
      if @departamento.save
        format.html { redirect_to @departamento, notice: 'Departamento was successfully created.' }
        format.json { render json: @departamento, status: :created, location: @departamento }
      else
        format.html { render action: "new" }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /departamentos/1
  # PUT /departamentos/1.json
  def update
    @departamento = Departamento.find(params[:id])

    respond_to do |format|
      if @departamento.update_attributes(params[:departamento])
        format.html { redirect_to @departamento, notice: 'Departamento was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @departamento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departamentos/1
  # DELETE /departamentos/1.json
  def destroy
    @departamento = Departamento.find(params[:id])
    @departamento.destroy

    respond_to do |format|
      format.html { redirect_to departamentos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/departamentos_helper.rb
module DepartamentosHelper
end

app/views/departamentos/_form.html.erb
<%= simple_form_for(@departamento) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :nome %>
    <%= f.association :unidade %>
  </div>

    <%= f.button :submit, "Salvar", class: "btn btn-primary" %>
    <%= link_to 'Voltar', departamentos_path, class: 'btn' %>
<% end %>

app/views/departamentos/edit.html.erb
<div class="page-header">
  <h1>Editar Departamento</h1>
</div>
<%= render 'form' %>

app/views/departamentos/index.html.erb
<div class="page-header">
	<h1>Departamentos</h1>
</div>
<% if (@departamentos.empty?) %>
	<%= bloco_vazio "Clique em Cadastrar Cadastrar Departamento.", "", class: "well span10 construcao" %>
<% else %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Departamento</th>
      <th>Unidade</th>
      <th>Nº de Professores</th>
      <th>Nº de Laboratórios</th>
    </tr>
  </thead>
  <tbody>
<% @departamentos.each do |departamento| %>
      <tr>
        <td><%= link_to departamento.nome , departamento %></td>
        <td><%= link_to departamento.unidade.nome , departamento.unidade %></td>
        <td>0</td>
        <td><%= departamento.laboratorios.count %></td>
        <td>
          <%= link_to "Informações", departamento, class: 'btn btn-small' %>
          <%= link_to "Editar", edit_departamento_path(departamento), class: 'btn btn-small' %>
          <%= link_to 'Remover', departamento_path(departamento), confirm: 'Tem certeza?', method: :delete, class: "btn btn-small btn-info" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>

<%= botao_com_icone "Cadastrar Departamento", new_departamento_path, "icon-plus icon-white", btn_class: "btn-primary" %>
<%= link_to 'Início', administracao_path, class: 'btn' %>

app/views/departamentos/new.html.erb
<div class="page-header">
  <h1>Cadastrar Departamento</h1>
</div>
<%= render 'form' %>

app/views/departamentos/show.html.erb
<div class="page-header">
	<h1><%= @departamento.nome %> <small> <%= @departamento.unidade.nome %></small></h1>
</div>
<div class="row-fluid linha-conteudo">
		<div class="well span5">
			<h3>Informações <small><%= botao_com_icone "Editar", edit_departamento_path(@departamento), "icon-edit icon-white", btn_class: "btn btn-mini btn-primary edit-button" %></small></h3>
			<hr>
			<dl>
				<dt>Nome do Departamento</dt>
				<dd><%= @departamento.nome %></dd>
				<dt>Unidade</dt>
				<dd><%= @departamento.unidade.nome %></dd>
				<dt>Coordenador</dt>
				<dd><%= link_to "Professor", "#" %></dd>
				<dt>Número de laboratórios vinculados</dt>
				<dd><%= @laboratorios.count %></dd>
			</dl>
		
		</div>
		<% if @departamento.laboratorios.empty? %>
			<% btn_vazio = botao_com_icone "Cadastrar Laboratório", novo_laboratorio_com_departamento_path(@departamento.id), "icon-plus icon-white", btn_class: "btn btn-primary btn-large alert-button" %>
			<%= bloco_vazio "Nenhum laboratório cadastrado neste departamento.", btn_vazio, class: "well span5 construcao" %>
		<% else %>
		<div class="well span5">
			<h3>Laboratórios Associados <small><%= botao_com_icone "Cadastrar Laboratório", novo_laboratorio_com_departamento_path(@departamento.id), "icon-plus icon-white", btn_class: "btn btn-primary btn-mini edit-button" %></small></h3>
			<hr>
			<table class="table table-striped">
				<thead>
					<th>Laboratorio</th>
					<th>Coordenador</th>
				</thead>
				<tbody>
				<% @departamento.laboratorios.each do |l| %>
					<td><%= link_to l, l %></td>
					<td>Professor</td>
				<% end %>	
				</tbody>
			</table>
		</div>
		<% end %>
</div>
<br />
<div class="row-fluid linha-conteudo">
	<%= bloco_contato contato: @contato, obj: @departamento, class: "span5" %>
	<%= bloco_vazio "Nenhum professor cadastrado neste departamento.", "", class: "well span5 construcao" %>
</div>

<br />
<%= link_to 'Editar', edit_departamento_path(@departamento), class: 'btn' %>
<%= link_to 'Voltar', departamentos_path, class: 'btn' %> 