config/routes.rb
Mapeamento::Application.routes.draw do

  
  get "sessions/new"

  resources :pessoas

  resources :contatos
  match "contatos/new/:obj_type/:obj_id" => 'contatos#new', as: "novo_contato"
  match "contatos/edit/:id/:obj_type/:obj_id" => 'contatos#edit', as: "editar_contato"

  resources :laboratorios

  resources :departamentos

  resources :unidades

  resources :redes, :except => :show do
    resources :palavras
  end
  root to: "application#home", as: "home"
  match 'administracao' => 'application#administracao', as: "administracao"
  match 'construcao' => 'application#under_construction'
  match 'laboratorios/new/:departamento_id' => 'laboratorios#new', as: "novo_laboratorio_com_departamento"
  match 'departamentos/new/:unidade_id' => 'departamentos#new', as: "novo_departamento_com_unidade"
  match 'palavras' => 'palavras#index'  
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/helpers/application_helper.rb
#!/bin/env ruby
# encoding: utf-8

module ApplicationHelper
  
  def carregar_menu(path)
    begin
      classe = /(\w+)(?=s)/.match(path)[1].capitalize.constantize
    rescue
      return nil
    end
    return classe.to_s
  end
  
  def botao_com_icone(texto = "", link = "#", icone = "icon-plus", args={})
    classe_icone = icone
    html_icone = content_tag(:i, "", class: classe_icone)
    html_btn = "btn #{args[:btn_class] if args[:btn_class]}"
    botao = link_to (html_icone + " " + texto), link, class: html_btn
  end
  
  def bloco_vazio (texto = "", btn = "", args={})
      titulo = content_tag :h3, "Vazio!" 
      p = content_tag :p, texto
      content_tag :div, (titulo + tag(:hr) + p + btn ), args
  end
  
  def flash_notice
    html = ""
    unless flash.empty?
      flash.each do |f|
        html << "<div class='alert alert-#{f[0].to_s}'>"
        html << "<a class='close' data-dismiss='alert'>×</a>"
        html << f[1].to_s
        html << "</div>"
      end
    else
      nil
    end
  end

  def bloco_contato(args={})
    contato = args[:contato]
    obj = args[:obj]
    html_class = args[:class] ? args[:class] : "" 
    quebra = tag :br
    if obj.contato.nil?
      botao = botao_com_icone "Cadastrar Contatos", novo_contato_path(obj.class, obj.id), "icon-plus icon-white", btn_class: "btn btn-primary btn-large" 
      bloco_vazio "Contatos não cadastrados", botao, class: "well span5 construcao"
    else
      
      botao = botao_com_icone "Editar", editar_contato_path(contato, obj.class, obj.id), "icon-edit icon-white", btn_class: "btn btn-mini btn-primary edit-button"
      btn_wraper = content_tag :small, botao
      texto_titulo = "Contatos"
      titulo = content_tag :h3, (texto_titulo + btn_wraper).html_safe
      telefone = content_tag(:i, "",class: "icon-th") + " Telefone: " + contato.telefone
      celular = content_tag(:i, "",class: "icon-th") + " Telefone: " + contato.celular
      email_icone = content_tag(:i, "",class: "icon-envelope")
      email_link = link_to @contato.email, "mailto:#{@contato.email}"
      email = email_icone + " Email: " + email_link
      bloco = content_tag :address, (telefone + quebra + celular + quebra + email)
      html_class += " well"
      s = content_tag :div, (titulo + tag(:hr) + bloco), id: "contato", class: html_class
    end
  end

end

app/views/application/_conteudo.html.erb
<% menu = carregar_menu(request.path) %>
<% if current_page?("/") %>
	<%= content_tag :div, yield, class: "welcome" %>
<% else %>
<div class="container-fluid conteudo_wrapper">
	<div class="row-fluid">	
		<div class="span2">
			<%= render "sidebar" %>
		</div>
		<%= content_tag :div, yield, class: "span10 page_front" %>
	</div>
</div>
<%= render "footer"%>
<% end %>

app/views/application/_footer.html.erb
			<footer>
				<div class="container">
					<div class="row">					
						<div class="span12">Agência de Inovação - Universidade Federal Fluminense</div>
					</div>
				</div>
			</footer>

app/views/application/_navbar.html.erb
    <div class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
          <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Mapa UFF de  Inovação", home_path, class: "brand" %>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
                <li><%= link_to "Redes Temáticas", redes_path  %></li>
                <li><%= link_to "Laboratórios", laboratorios_path  %></li>
                <li><%= link_to "Departamentos", departamentos_path  %></li>
                <li><%= link_to "Unidades", unidades_path  %></li>
				<li><%= link_to "Professores", construcao_path  %></li>
				<li><%= link_to "Administração", administracao_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

app/views/application/_sidebar.html.erb
	<div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Administração</li>
              <li><%= link_to "Início", administracao_path  %></li>
              <li><%= link_to "Redes Temáticas", redes_path  %></li>
              <li><%= link_to "Laboratórios", laboratorios_path  %></li>
              <li><%= link_to "Departamentos", departamentos_path  %></li>
              <li><%= link_to "Unidades", unidades_path  %></li>
            </ul>
          </div><!--/.well -->

app/views/application/administracao.html.erb
<div class="container-fluid">
	<div class="row-fluid item-line">
		<div class="span5">
			<%= link_to image_tag('rede.png'), redes_path %>
			<p class="item">
				<%= link_to "Redes Temáticas", redes_path %>
			</p>
		</div>
		<div class="span5">
			<%= link_to image_tag('laboratorio.png'), laboratorios_path %>
			<p class="item">
				<%= link_to "Laboratorios", laboratorios_path %>
			</p>
		</div>
	</div>
	<div class="row-fluid item-line">
		<div class="span5">
			<%= link_to image_tag('departamento.png'), departamentos_path %>
			<p class="item">
				<%= link_to "Departamentos", departamentos_path %>
			</p>
		</div>
		<div class="span5">
			<%= link_to image_tag('unidade.png'), unidades_path %>
			<p class="item">
				<%= link_to "Unidades de Ensino", unidades_path %>
			</p>
		</div>
	</div>
	<div class="row-fluid item-line">
		<div class="span5">
			<%= link_to image_tag('professor.png'), construcao_path %>
			<p class="item">
				<%= link_to "Professores", construcao_path %>
			</p>
		</div>
	</div>
</div>

app/views/application/home.html.erb
<div class="front-card-wrapper">
	<div class="row">
		<div class="front-card span5">
			<h1>Mapa UFF de Inovação</h1>
			<hr>
			<p>
				Descubra os laboratórios, núcleos de pesquisa e competências da Universidade Federal Fluminense
			</p>
		</div>
		<div class="front-card-rigth span4">
			<div class="front-card">
				 <input type="text" placeholder="Usuário">
				 <input type="text" placeholder="Senha">
				 <%= link_to "Entrar", administracao_path, class: "btn"%>
				 <%= link_to "Cadastrar-se", new_pessoa_path, class: "btn"%>
			</div>
		</div>
	</div>
</div>

app/views/application/under_construction.html.erb
<div class="hero-unit construcao">
	<%= image_tag('construction.png') %>
	<h2>
		Esta seção ainda está sendo construída.
	</h2>
		<p>alexandre.abreu.uff@gmail.com</p>
		<%= link_to "Voltar", :back, class: "btn btn-large" %>
</div>